//! `chunks` table: retrieval chunks for semantic search / RAG (design §9).
//!
//! Each chunk carries its text window, `start_ms`/`end_ms`, an optional
//! diarized `local_idx`, and a `halfvec(768)` embedding (half precision to halve
//! the HNSW index size at negligible recall loss). The `tsv` keyword column is
//! generated by the database.

use pgvector::HalfVector;
use scribe_core::types::Chunk;
use scribe_core::Result;
use sqlx::postgres::PgRow;
use sqlx::Row;
use uuid::Uuid;

use crate::db_err;
use crate::Db;

/// Input for inserting a retrieval chunk. The embedding is the text-embedding
/// model's output (768-dim, stored as `halfvec`).
#[derive(Debug, Clone)]
pub struct NewChunk {
    pub start_ms: Option<i64>,
    pub end_ms: Option<i64>,
    pub local_idx: Option<i32>,
    pub text: String,
    pub embedding: Vec<f32>,
}

impl Db {
    /// Bulk-insert chunks for a recording. Returns the number inserted.
    ///
    /// Each embedding is converted to `halfvec` via [`HalfVector::from_f32_slice`].
    /// We bind one row per chunk (rather than `unnest`) because there is no array
    /// binding for `halfvec[]` in pgvector 0.4; the inserts share one transaction.
    pub async fn insert_chunks(&self, recording_id: Uuid, chunks: &[NewChunk]) -> Result<u64> {
        if chunks.is_empty() {
            return Ok(0);
        }
        let mut tx = self.pool().begin().await.map_err(db_err)?;
        let mut inserted = 0u64;
        for c in chunks {
            let embedding = HalfVector::from_f32_slice(&c.embedding);
            inserted += sqlx::query(
                "INSERT INTO chunks (recording_id, start_ms, end_ms, local_idx, text, embedding) \
                 VALUES ($1, $2, $3, $4, $5, $6)",
            )
            .bind(recording_id)
            .bind(c.start_ms)
            .bind(c.end_ms)
            .bind(c.local_idx)
            .bind(&c.text)
            .bind(&embedding)
            .execute(&mut *tx)
            .await
            .map_err(db_err)?
            .rows_affected();
        }
        tx.commit().await.map_err(db_err)?;
        Ok(inserted)
    }

    /// Delete all chunks for a recording (for re-embedding). Returns the count.
    pub async fn delete_chunks_by_recording(&self, recording_id: Uuid) -> Result<u64> {
        let affected = sqlx::query("DELETE FROM chunks WHERE recording_id = $1")
            .bind(recording_id)
            .execute(self.pool())
            .await
            .map_err(db_err)?
            .rows_affected();
        Ok(affected)
    }

    /// List chunks for a recording in time order. The embedding is not returned
    /// (it is large and rarely needed by callers); `Chunk::embedding` is `None`.
    pub async fn list_chunks_by_recording(&self, recording_id: Uuid) -> Result<Vec<Chunk>> {
        let rows = sqlx::query(
            "SELECT id, recording_id, start_ms, end_ms, text \
             FROM chunks WHERE recording_id = $1 ORDER BY start_ms, id",
        )
        .bind(recording_id)
        .fetch_all(self.pool())
        .await
        .map_err(db_err)?;
        rows.iter().map(chunk_from_row).collect()
    }
}

fn chunk_from_row(row: &PgRow) -> Result<Chunk> {
    Ok(Chunk {
        id: row.try_get("id").map_err(db_err)?,
        recording_id: row.try_get("recording_id").map_err(db_err)?,
        start_ms: row.try_get("start_ms").map_err(db_err)?,
        end_ms: row.try_get("end_ms").map_err(db_err)?,
        text: row.try_get("text").map_err(db_err)?,
        embedding: None,
    })
}
