//! `utterances` table: the speaker-labelled transcript (design §8/§10).
//!
//! Each row is one utterance / speaker turn. `words` is the word-level timing
//! array, stored as jsonb. The `tsv` keyword-search column is generated by the
//! database from `text`, so we never write it.

use scribe_core::types::{Utterance, Word};
use scribe_core::Result;
use sqlx::postgres::PgRow;
use sqlx::Row;
use uuid::Uuid;

use crate::db_err;
use crate::Db;

/// Input for inserting a transcript turn. `id` is assigned by the database, so
/// callers supply only the content; `words` is serialized to the jsonb column.
#[derive(Debug, Clone)]
pub struct NewUtterance {
    /// Diarized speaker index, or `None` before merge.
    pub local_idx: Option<i32>,
    pub start_ms: i64,
    pub end_ms: i64,
    pub text: String,
    pub words: Vec<Word>,
}

impl Db {
    /// Bulk-insert utterances for a recording. Returns the number inserted.
    /// Uses an unnest-based multi-row insert so the whole batch is one round
    /// trip; `words` is serialized to jsonb per row.
    pub async fn insert_utterances(
        &self,
        recording_id: Uuid,
        utterances: &[NewUtterance],
    ) -> Result<u64> {
        if utterances.is_empty() {
            return Ok(0);
        }

        let mut local_idxs: Vec<Option<i32>> = Vec::with_capacity(utterances.len());
        let mut starts: Vec<i64> = Vec::with_capacity(utterances.len());
        let mut ends: Vec<i64> = Vec::with_capacity(utterances.len());
        let mut texts: Vec<String> = Vec::with_capacity(utterances.len());
        let mut words: Vec<serde_json::Value> = Vec::with_capacity(utterances.len());

        for u in utterances {
            local_idxs.push(u.local_idx);
            starts.push(u.start_ms);
            ends.push(u.end_ms);
            texts.push(u.text.clone());
            words.push(serde_json::to_value(&u.words)?);
        }

        // unnest the parallel arrays into rows. `$2::int[]` may carry NULLs, so
        // we cast each array to its element type explicitly.
        let affected = sqlx::query(
            "INSERT INTO utterances (recording_id, local_idx, start_ms, end_ms, text, words) \
             SELECT $1, l, s, e, t, w \
             FROM unnest($2::int[], $3::bigint[], $4::bigint[], $5::text[], $6::jsonb[]) \
               AS x(l, s, e, t, w)",
        )
        .bind(recording_id)
        .bind(&local_idxs)
        .bind(&starts)
        .bind(&ends)
        .bind(&texts)
        .bind(&words)
        .execute(self.pool())
        .await
        .map_err(db_err)?
        .rows_affected();
        Ok(affected)
    }

    /// Delete all utterances for a recording (for reprocessing). Returns the count.
    pub async fn delete_utterances_by_recording(&self, recording_id: Uuid) -> Result<u64> {
        let affected = sqlx::query("DELETE FROM utterances WHERE recording_id = $1")
            .bind(recording_id)
            .execute(self.pool())
            .await
            .map_err(db_err)?
            .rows_affected();
        Ok(affected)
    }

    /// The full transcript for a recording in time order, each utterance carrying
    /// the resolved speaker name (joined via `recording_speakers` → `speakers`,
    /// defaulting to `"Speaker N"`).
    pub async fn list_utterances_by_recording(
        &self,
        recording_id: Uuid,
    ) -> Result<Vec<Utterance>> {
        let rows = sqlx::query(
            "SELECT u.id, u.recording_id, u.local_idx, u.start_ms, u.end_ms, u.text, u.words, \
                    s.display_name AS speaker_name \
             FROM utterances u \
             LEFT JOIN recording_speakers rs \
               ON rs.recording_id = u.recording_id AND rs.local_idx = u.local_idx \
             LEFT JOIN speakers s ON s.id = rs.speaker_id \
             WHERE u.recording_id = $1 \
             ORDER BY u.start_ms, u.id",
        )
        .bind(recording_id)
        .fetch_all(self.pool())
        .await
        .map_err(db_err)?;
        rows.iter().map(utterance_from_row).collect()
    }
}

fn utterance_from_row(row: &PgRow) -> Result<Utterance> {
    let local_idx: Option<i32> = row.try_get("local_idx").map_err(db_err)?;
    let words_json: serde_json::Value = row.try_get("words").map_err(db_err)?;
    let words: Vec<Word> = serde_json::from_value(words_json)?;
    let resolved: Option<String> = row.try_get("speaker_name").map_err(db_err)?;
    // If matched, use the real name; otherwise fall back to the diarized label.
    let speaker_name = resolved.or_else(|| local_idx.map(|i| format!("Speaker {i}")));
    Ok(Utterance {
        id: row.try_get("id").map_err(db_err)?,
        recording_id: row.try_get("recording_id").map_err(db_err)?,
        local_idx,
        start_ms: row.try_get("start_ms").map_err(db_err)?,
        end_ms: row.try_get("end_ms").map_err(db_err)?,
        text: row.try_get("text").map_err(db_err)?,
        words,
        speaker_name,
    })
}
